version: '3'

services:
  client:
    image: node:10.15.3-alpine
    volumes:
      - ./client:/src
    working_dir: /src
    command: [sh, -c, npm i -g gulp && npm i && gulp]
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - server
  
  server:
    image: node:10.15.3-alpine
    volumes:
      - ./server:/src
    working_dir: /src
    command: [sh, -c, npm i -g nodemon && npm i && nodemon main.js]
    tty: true
    ports:
      - 3001:3001
  
  nginx:
    image: nginx:1.16.0-alpine
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./client:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server
